language:
  - python

# Install ansible
#addons:
#  apt:
#    packages:
#    - python-pip

install:
  # Install ansible
  - pip install ansible
  # install galaxy role
  - ansible-galaxy install PaloAltoNetworks.paloaltonetworks
  # instasll pep8
  - pip install pycodestyle

script:
  # Perform unittests
  #- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Verify style guidelines are met
  - cd library; find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402,E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505 {} +

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
