---
dependencies: []

galaxy_info:
  role_name: solr
  author: geerlingguy
  description: Apache Solr for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - solr
    - search
    - lucene
    - container
    - apache
    - text
