---
- name: Converge
  hosts: all
  vars:
    authorized_key_users:
      - username: 'root'
        key: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
  roles:
    - role: arillso.authorized_key
