---
galaxy_info:
  role_name: ca-certificates
  author: arillso
  description: Install certificates from a file or url under Windows and Linux.
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 29
    - name: Ubuntu
      versions:
        - bionic
        - cosmic
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - ca
    - certificates

dependencies: []
