---
dependencies:
  - geerlingguy.apache
  - geerlingguy.mysql
  - geerlingguy.php-mysql
  - geerlingguy.php

galaxy_info:
  author: geerlingguy
  description: phpMyAdmin installation for Linux
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - database
    - development
    - web
    - mysql
    - mariadb
    - php
    - phpmyadmin
