---
# tasks file for arillso.authorized_key

- name: 'linux : include tasks'
  include_tasks: subtasks/authorized_key.yml
  loop: '{{ authorized_key_users }}'
  loop_control:
    loop_var: loop_authorized_key_user
